site_name: Paramiko Mock
theme:
  name: material
nav:
  - Home: index.md
  - Usage: usage.md
plugins:
  - search
  - mkdocs-autoapi:
      autoapi_dir: src
      autoapi_add_nav_entry: true
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format